#!/bin/bash

echo "##################### Existing Shorewall configurations"
echo " "
echo "************ ALLOW SSH MACRO"
cat /etc/shorewall/macro.ALLOW_SSH | grep PARAM
echo " "
echo " "
echo "************ ALLOW MYSQL MACRO"
cat /etc/shorewall/macro.MYSQL | grep PARAM
echo " "
echo " "
echo " "
echo "##################### Imunify Configuratoins"
echo " "
echo "************ ALLOW SSH FILE"
cat /etc/imunify360/whitelist/ALLOW_SSH.txt
echo " "
echo " "
echo "************ ALLOW MYSQL FILE"
cat /etc/imunify360/whitelist/MYSQL.txt
echo " "
echo " "
echo "############ Fail2ban jail.conf Enteries"
cat /etc/fail2ban/jail.conf | grep "ignoreip "
echo " "
echo " "
echo "************ PAM module status"
imunify360-agent config show | jq '.PAM | keys'
echo " "
echo " "
echo " "
systemctl status fail2ban

